name: Test Build Pdf

on: [push, pull_request]

jobs:
  html_to_pdf:
    name: Generate PDF
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Setup Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1

      - name: html to pdf
        uses: LukaszLapaj/html-to-pdf-action@master
        with:
          htmlFile: ./example.html
          outputFile: ./example.pdf
          pdfOptions: '{"margin": {"top": "1px", "left": "100px", "right": "100px", "bottom": "100px"}}'

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Example PDF
          path: ./example.pdf